language: generic
sudo: required
services:
  - docker
  
before_install:
  - docker build -t bdexley5/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true bdexley5/docker-react npm run test -- --coverage
  